spring.datasource.url=jdbc:mysql://bmr2g8jplbckhleip4q3-mysql.services.clever-cloud.com:3306/bmr2g8jplbckhleip4q3
spring.datasource.username=u4bcv2ukrxk43jve
spring.datasource.password=8enQMLGuSTkHPPHRGmWT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This automatically creates your database tables on Clever Cloud
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=2